import type { Metadata } from "next";
import "@src/css/globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={""}
      >
      {children}
      </body>
    </html>
  );
}
